### ISSUE TITLE
Hide during cutscenes

### ISSUE THREAD

**Issue by Razimus** [HealsCodes/statustimers#17]
Hi, adding this request as per your message on discord. Really like the addon.

Thanks.

**Comment by Razimus** [comment]
Sorry I forgot to add that it would be great if it could also hide itself when you open the map.

**Comment by Erebos333** [comment]
all the above but also the option to hide when chat is maximised too please :)

**Comment by darkedone02** [comment]
I want this too.

**Comment by HealsCodes** [comment]
Will be fixed with v4.1.503 - sorry for the delay, IRL's been busy.
